[project]
name = "ai-engineer-cohort"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abhishekkrsinghdev", email = "hrithiksinghrocks31@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "openai>=1.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
ai-engineer-cohort = "ai_engineer_cohort:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
